# -*- coding: utf-8 -*-
"""CIE1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qYGfGLu-SCcajgdZNy4K7cTPCLD3tWFP
"""

import pandas as pd
data = pd.read_csv('/content/mtcars.csv')
data

import matplotlib.pyplot as plt
plt.hist(data['mpg'], bins=10, edgecolor='black')
plt.xlabel('mpg')
plt.ylabel('freuency')
plt.title('historam of mpg')
plt.show()

import matplotlib.pyplot as plt
plt.scatter(data['wt'],data['mpg'],color='r',edgecolor='black')
plt.title('scatter plot of mpg')
plt.xlabel('wt')
plt.ylabel('mpg')
plt.show()

import matplotlib.pyplot as plt
plt.figure(figsize=(10, 6))
transmission_counts.plot(kind='bar')
plt.title('Frequency Distribution of Transmission Types')
plt.xlabel('Transmission (0 = Automatic, 1 = Manual)')
plt.ylabel('Frequency')
plt.xticks(rotation=0)
plt.show()

